import { readFileSync } from 'fs';
import { join } from 'path';

interface MovementRow {
  movementAt: Date;
  movementType: 'ENTRY' | 'EXIT';
}

interface ReportData {
  companyName: string;
  employeeName: string;
  employeeCode: string;
  dateLabel: string;
  movements: MovementRow[];
}

// Logo embedded as a base64 data URI so Puppeteer can render it offline,
// with no network fetch during report generation. Read lazily and cached
// rather than at module load — a missing/stale asset path must only ever
// fail the report-generation call, never crash the whole app at boot
// (the same lesson as EmailService's lazy Resend client).
let cachedLogoDataUri: string | null = null;
function getLogoDataUri(): string {
  if (!cachedLogoDataUri) {
    const buffer = readFileSync(join(__dirname, 'assets', 'adage-logo.png'));
    cachedLogoDataUri = `data:image/png;base64,${buffer.toString('base64')}`;
  }
  return cachedLogoDataUri;
}

// Real structured HTML report — deliberately NOT a screenshot of a live
// page (spec §34) — rendered to PNG/PDF via headless browser (decision:
// Puppeteer, one template for both formats).
export function renderMovementReportHtml(data: ReportData): string {
  const rows = data.movements
    .map(
      (m) => `
        <div class="row">
          <span class="time">${formatTime(m.movementAt)}</span>
          <span class="type ${m.movementType === 'ENTRY' ? 'entry' : 'exit'}">${m.movementType}</span>
        </div>`,
    )
    .join('');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: 'Segoe UI', Arial, sans-serif;
    background: #ffffff;
    color: #14201f;
    width: 720px;
    padding: 48px;
  }
  .brand-logo { display: block; height: 40px; margin: 0 auto 12px; }
  .title { text-align: center; font-size: 15px; font-weight: 700; letter-spacing: 2px; color: #64756f; margin-top: 4px; margin-bottom: 32px; text-transform: uppercase; }
  .field { margin-bottom: 10px; font-size: 15px; }
  .field .label { color: #64756f; }
  .field .value { font-weight: 700; }
  .divider { border-top: 2px solid #0d828b; margin: 24px 0; }
  .row { display: flex; justify-content: space-between; padding: 10px 4px; font-size: 16px; border-bottom: 1px solid #eee; }
  .time { font-weight: 600; }
  .type { font-weight: 800; letter-spacing: 1px; }
  .type.entry { color: #15803d; }
  .type.exit { color: #be123c; }
  .footer { text-align: center; margin-top: 32px; font-size: 12px; color: #888; }
</style>
</head>
<body>
  <img class="brand-logo" src="${getLogoDataUri()}" alt="${escapeHtml(data.companyName)}" />
  <div class="title">Employee Movement Record</div>

  <div class="field"><span class="label">Employee: </span><span class="value">${escapeHtml(data.employeeName)}</span></div>
  <div class="field"><span class="label">Employee ID: </span><span class="value">${escapeHtml(data.employeeCode)}</span></div>
  <div class="field"><span class="label">Date: </span><span class="value">${escapeHtml(data.dateLabel)}</span></div>

  <div class="divider"></div>
  ${rows || '<div class="row"><span>No movement records for this date.</span></div>'}
  <div class="divider"></div>

  <div class="footer">Generated by ${escapeHtml(data.companyName)} Security System</div>
</body>
</html>`;
}

function formatTime(date: Date): string {
  return new Intl.DateTimeFormat('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true }).format(date);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
